### ISSUE TITLE
Issue with Websocket connection

### ISSUE THREAD

**Issue by ItsLeon15** [BL00DY-C0D3/Echo-VR-Server-on-Docker#7]
I successfully ran the ``install.sh`` script which setup all of the docker containers but whenever I try and test a website like ``ws://x.x.x.x:2782/config`` it doesn't work and the connection closes. Am I doing something wrong? Any help is appreciated.

**Comment by marshmallow-mia** [comment]
Hey, 
There is no website behind it.
ws:// just defines the WebSocket protocol.

Additionally the information you enter to configure the server, needs to show on an EchoRelay.
You can always change them inside the config.json on your ready-at-dawn-echo-arena/_local folder without restarting the install script.

The server need to connect to an EchoRelay, and the Echo VR Clients are connecting to the relay as well.
The relay then forwards the connection from the Client to the Server.

If you want to set up a relay, you can check here:

https://github.com/EchoTools/EchoRelay

I never got it to work on the same VM tho.
It redirected clients to the private IP instead of the public one for some reason.

**Comment by marshmallow-mia** [comment]
> I successfully ran the `install.sh` script which setup all of the docker containers but whenever I try and test a website like `ws://x.x.x.x:2782/config` it doesn't work and the connection closes. Am I doing something wrong? Any help is appreciated.

Is there something else you need help with?

**Comment by ItsLeon15** [comment]
No thanks, your explanation helped a lot. Just forgot to close the issue.
